name = "english-learning"
main = ".open-next/worker.js"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[env.local]
vars = { JWT_SECRET = "dev-secret-key-change-this-for-production" }

[[env.local.d1_databases]]
binding = "DB"
database_name = "english-learning-db"
database_id = "00000000-0000-0000-0000-000000000000"

[assets]
binding = "ASSETS"
directory = ".open-next/assets"

[observability]
enabled = true