name = "english-learning"
main = ".open-next/worker.js"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[env.local]
vars = { JWT_SECRET = "dev-secret-key-change-this-for-production" }

[[env.local.d1_databases]]
binding = "DB"
database_name = "english-learn"
database_id = "6d8bb437-6607-4a32-9d74-155362f42687"

[assets]
binding = "ASSETS"
directory = ".open-next/assets"

[observability]
enabled = true